### ISSUE TITLE
x86_64-linux not set in PERL5LIB

### ISSUE THREAD

**Issue by ylavoie** [shogo82148/actions-setup-perl#1263]
Shouldn't `x86_64-linux` be included in the PERL5LIB provided to the user?
For example, this:
```
      - name: Setup Perl environment
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: 5.34
          install-modules-with: cpanm
          install-modules: |
            Devel::Cover
            Devel::Cover::Report::Coveralls
            Syntax::Keyword::Try
            Syntax::Keyword::Try::Deparse
          # Features and Devel modules
          install-modules-args: >
            --metacpan
            --with-develop
            --with-feature=starman
```
Will install `Deparse.pm` in
```
/home/runner/work/_temp/72798feb-334e-4916-9855-9c61eea578b1/lib/5.34.1/B/Deparse.pm
${GITHUB_WORKSPACE}/local/lib/perl5/x86_64-linux/Syntax/Keyword/Try/Deparse.pm
```
while the `PERL5LIB` provided only contains
```
PERL5LIB=${GITHUB_WORKSPACE}/local/lib/perl5:/home/runner/work/_actions/shogo82148/actions-setup-perl/v1/scripts/lib
```
thus forcing Perl to rely on the system installed version of the module, which doesn't match the Perl version.

It is often of no consequences for most modules, except those which are compiled for a specific Perl version, such as `Devel::Cover` or `Syntax::Keyword::Try::Deparse`

**Comment by shogo82148** [comment]
memo:
we should emulate https://metacpan.org/pod/local::lib

**Comment by shogo82148** [comment]
https://metacpan.org/dist/perl/source/lib/blib.pm
