### ISSUE TITLE
The `set-output` command is deprecated 

### ISSUE THREAD

**Issue by pmqs** [shogo82148/actions-setup-perl#1300]
Seeing this warning in my latest actions run
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

Is this an issue with `actions-setup-perl` ?

For an example see https://github.com/pmqs/zipdetails/actions/runs/3281801176/jobs/5404317013

**Comment by shogo82148** [comment]
It will be fixed by https://github.com/shogo82148/actions-setup-perl/pull/1267, https://github.com/shogo82148/actions-setup-perl/pull/1293 and https://github.com/shogo82148/actions-setup-perl/pull/1288.
Please be patient for next release. I'll merge pull-requests and release them soon.

**Comment by pmqs** [comment]
Thanks.

Looking at https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ it seems like you have until  31st May 2023 to deal with it.

Closing this issue
