### ISSUE TITLE
setupperl.blob.core.windows.net server not found, unable to install Strawberry Perl

### ISSUE THREAD

**Issue by m-dango** [shogo82148/actions-setup-perl#1350]
The URL defined in https://github.com/shogo82148/actions-setup-perl/blob/main/src/strawberry.ts#L104 for downloading Strawberry Perl appears to be inaccessible/unavailable.

**Comment by shogo82148** [comment]
oops, it's my fault.
I'll fix it soon.

**Comment by dk** [comment]
Hi 

I see this bug has been addressed, but I'm still getting "Error: getaddrinfo ENOTFOUND setupperl.blob.core.windows.net" on my github actions. Do you possibly have a hint where I need to push github so it will reload a newer version if actions-setup-perl? (assuming the URL shogo82148/actions-setup-perl@v1 is still correct?)

thank you!

**Comment by shogo82148** [comment]
I've just released https://github.com/shogo82148/actions-setup-perl/releases/tag/v1.18.3 and update the v1 tag.
The issue is fixed by this release.
