### ISSUE TITLE
Error about missing .python-version file

### ISSUE THREAD

**Issue by ferki** [shogo82148/actions-setup-perl#1369]
My workflows using `shogo82148/actions-setup-perl@v1` started to fail today with the following error message:

> Error: ENOENT: no such file or directory, open '/home/runner/work/Rex/Rex/.python-version'

Based on quick grepping of the codebase, it is probably related to [this line](https://github.com/shogo82148/actions-setup-perl/blob/v1.20.0/src/setup-perl.ts#L109), which was recently added to v1.20.0 as part of `.perl-version` file support via #1367.

My first instinct was to send a pull request to replace the`.python-version` filename with `.perl-version`. I'm afraid it would still result in a similar error when there is no `perl-version` option, and the repo does not have a `.perl-version` file (previously it was defaulting to `5`).

Therefore I decided to open an issue instead, and learn more about how it would be best to address.

**Comment by shogo82148** [comment]
Thank you for your report!
I'll fix it.

**Comment by shogo82148** [comment]
I released https://github.com/shogo82148/actions-setup-perl/releases/tag/v1.20.1
Please try it!

**Comment by ferki** [comment]
Looks working again, thanks! :+1:
