### ISSUE TITLE
$GITHUB_WORKDIR/local is unexpectedly added to @INC

### ISSUE THREAD

**Issue by mauke** [shogo82148/actions-setup-perl#1474]
Something in this action is adding the `local` subdirectory of my checkout to `@INC`, so when I run `make test`, perl loads modules from `local`. I don't want that. (And it doesn't seem to be documented, either.)

**Comment by mauke** [comment]
... and I just realized `local` is automatically cached between runs, so not only does perl (via `make test`) use the wrong files, renaming my `local` directory to a different name doesn't fix it. Because of caching, the wrong files are now semi-permanently part of the build until I manually delete all ~100 of my caches.

There should be a big warning in the README that tells users not to name a directory `local`, or things break in weird ways.

**Comment by shogo82148** [comment]
Caching can be disabled by specifying `enable-modules-cache: false`.
https://github.com/shogo82148/actions-setup-perl#enable-modules-cache

> There should be a big warning in the README that tells users not to name a directory local, or things break in weird ways.

I agree. Can you send me a pull request that fixes it?

**Comment by mauke** [comment]
Oh, I didn't know that setting applied because the documentation says:

> Enable caching when install CPAN modules.

I'm not using `install-modules` and the README says modules are not installed by default, so I figured it wouldn't do anything. (Also, I don't have a `cpanfile`, so where is it getting the cache key from?)

**Comment by mauke** [comment]
My pull request: https://github.com/shogo82148/actions-setup-perl/pull/1475

(By the way, thank you for creating this action. It makes matrix-testing my modules so much easier.)

**Comment by shogo82148** [comment]
https://github.com/shogo82148/actions-setup-perl/pull/1475 is already merged.
