### ISSUE TITLE
Has CPAN::Meta::Requirements been Removed?

### ISSUE THREAD

**Issue by theory** [shogo82148/actions-setup-perl#1549]
Not sure when it might have happened, but noticed in [this build](https://github.com/sqitchers/sqitch/actions/runs/5366655603/jobs/9736259326).

**Comment by shogo82148** [comment]
Oh, sorry
It's my fault. https://github.com/shogo82148/actions-setup-perl/pull/1519

**Comment by shogo82148** [comment]
It is fixed by https://github.com/shogo82148/actions-setup-perl/pull/1550 and I just released [v1.21.3](https://github.com/shogo82148/actions-setup-perl/releases/tag/v1.21.3).

**Comment by theory** [comment]
Thank you, builds are happy again!
