### ISSUE TITLE
Add Universal CRT?

### ISSUE THREAD

**Issue by theory** [shogo82148/actions-setup-perl#1713]
In troubleshooting [an issue with locales on Windows](https://stackoverflow.com/q/77771097/79202), it seems that the solution to allow UTF-8 locales, according to [this PerlMonks thread](https://www.perlmonks.org/?node_id=11153468), is to include the [Universal CRT](https://learn.microsoft.com/en-us/cpp/porting/upgrade-your-code-to-the-universal-crt?view=msvc-170). From [this comment in September](https://www.perlmonks.org/?node_id=11154370), it sounds like Perl 5.39.2 uses it, but other versions would need patching? Not sure if that's a possibility. For now I'm skipping localization tests on Windows.

See also StrawberryPerl/Perl-Dist-Strawberry#152 and also [this comment](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/150#issuecomment-1784955524), which appears to demonstrate the ability to set a locale like `en_US.UTF-8`, which is ideal for my tests.

**Comment by shogo82148** [comment]
I'm not going to fix this issue.

This project aims to replicate past versions of Perl, including their bugs.

**Comment by theory** [comment]
I can understand why you'd not do anything with this (it requires patching!), but I'm not sure I'd call it a bug in Perl. Well, maybe? I dunno, it's arguable.

Here's hoping Perl 5.40 or an updated Strawberry compiles with UCRT.
