### ISSUE TITLE
install of Perl 5.18 fails on Windows

### ISSUE THREAD

**Issue by atoomic** [shogo82148/actions-setup-perl#222]
```
Run shogo82148/actions-setup-perl@v1.3.0
  with:
    perl-version: 5.18.4
##[error](s || "").replace is not a function
```
more details from https://github.com/atoomic/B-COW/runs/656749538?check_suite_focus=true

**Comment by shogo82148** [comment]
because the pre-built binary for 5.18.4 was broken.
I rebuilt and fixed it.
