### ISSUE TITLE
Perl Build 5.20 Failing on macOS

### ISSUE THREAD

**Issue by theory** [shogo82148/actions-setup-perl#231]
Reference: https://github.com/theory/semver/runs/681420693

Not much of use in [the logs](https://pipelines.actions.githubusercontent.com/gcjFXuahFoaYfxz59DCTXjDGUVLUgEZbe2rKSAu6BWBUTITY7s/_apis/pipelines/1/runs/23/signedlogcontent/13?urlExpires=2020-05-16T19%3A40%3A51.3973162Z&urlSigningMethod=HMACV1&urlSignature=Fv26j8TXdK2WdJmpZfan%2FTFOwzZwmi8OJgj3zycFojM%3D), either. :-(

**Comment by shogo82148** [comment]
![image](https://user-images.githubusercontent.com/1157344/82131846-92ed1400-9814-11ea-8799-54ed29a100cf.png)

Oh... Perl 5.20.3 on macOS is missing...
I'll rebuild it.

**Comment by shogo82148** [comment]
Done
![image](https://user-images.githubusercontent.com/1157344/82133319-ce440e80-9825-11ea-8d9c-b62e6ce6842d.png)

I'll create the release binary checker or something else.

**Comment by theory** [comment]
Better now, thanks.
