### ISSUE TITLE
Windows Testing

### ISSUE THREAD

**Issue by genio** [shogo82148/actions-setup-perl#235]
Hi!

Thank you for creating this! It works perfectly on Mac and Linux. I am, however, having issues running tests on Windows (one problem I think you're aware of already).  However, I come bringing possible solutions.

https://github.com/p5-UV/Alien-libuv/blob/master/.github/workflows/windows.yml I am using this setup now. It's using a friend's S3 bucket site mirror for Strawberry Perl's site. It fixes the problem of not being able to test on any version. It saves you from actually having to build Perl on the Windows machine with MinGW.

If you can alter your actions to use this method along with your caching mechanism, it would allow you to have working tests on Windows for any version of Perl where there's a portable.

Running this particular set of tests I linked to above was taking around 10 minutes per run on AppVeyor and now runs in around 2 minutes and 30 seconds on GitHub Actions. It allows testing both pure Perl and XS modules and already has cpanm setup from the beginning.

Thoughts?

**Comment by shogo82148** [comment]
strawberry perl is available on https://github.com/shogo82148/actions-setup-perl/releases/tag/v1.5.0
enjoy hacking!

**Comment by genio** [comment]
By default, windows-latest comes with Strawberry Perl installed. This needs to be removed from the PATH. When you then download and run a portable strawberry, those paths need to be added to the PATH. It looks like we're seeing:

```2020-06-19T21:06:40,5944| You have make C:\Strawberry\c\bin\gmake.EXE```

Attempting to build/install with the version that comes already installed vs using the portable you're asking for in the workflow file.

See the example here:
https://github.com/p5-UV/Alien-libuv/blob/master/.github/workflows/windows.yml#L31-L39

**Comment by shogo82148** [comment]
Oh, I forgot to add `C:\straw\perl\site\bin` to the `PATH`.

I'll fix it.

**Comment by genio** [comment]
Got this one working today! https://github.com/perhunter/slurp/blob/master/.github/workflows/windows.yml  Works well.  Thank you again!
