### ISSUE TITLE
Please document the default Perl version used when no version is specified

### ISSUE THREAD

**Issue by skirmess** [shogo82148/actions-setup-perl#321]
It seems to be using the latest version. Is that guaranteed behavior? Or would it be possible to support something like?

`perl: latest`

**Comment by shogo82148** [comment]
> It seems to be using the latest version. Is that guaranteed behavior?

No, the default Perl version is now "5". It means the latest version of Perl 5.
As you know, Perl 7 will be released in next year.
After that, the default version is not latest.

> Or would it be possible to support something like?

OK. I will try it.

**Comment by skirmess** [comment]
So, the default is 5, which will always be the latest Perl 5.x available? That's fine then. I wasn't sure if that was just by luck or is guaranteed.

**Comment by shogo82148** [comment]
Yes, the latest Perl 5.x available will be used.
But it may be changed after releasing Perl 7. Because I didn't know about Perl 7 when I created actions-setup-perl.
