### ISSUE TITLE
cpanm --installdeps

### ISSUE THREAD

**Issue by lskatz** [shogo82148/actions-setup-perl#349]
cpanm mysteriously does not install modules for me either. For example: https://github.com/lskatz/endopep_peaks/runs/1161249764?check_suite_focus=true

e.g., `cpanm -l $HOME --installdeps --verbose --force .` does not read correctly from `Makefile.PL`

Sort of like #225 

However, direct installations do work like https://github.com/lskatz/endopep_peaks/actions/runs/271010996

e.g., `cpanm -l $HOME File::Which --force --notest --verbose`

**Comment by shogo82148** [comment]
It's not a problem of actions-setup-perl.

Your `Makefile.PL` drops the `prereqs` section of `MYMETA.json` with ExtUtils::MakeMaker version 6.6302 (bundled with Perl 5.16.3).

https://github.com/shogo82148/endopep_peaks/actions/runs/274873475

```json
{
  "abstract": "unknown",
  "author": [
    "Lee S. Katz <gzu2@cdc.gov>"
  ],
  "dynamic_config": 0,
  "generated_by": "ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630",
  "license": [
    "mit"
  ],
  "meta-spec": {
    "url": "http://search.cpan.org/perldoc?CPAN::Meta::Spec",
    "version": "2"
  },
  "name": "Endopep_peaks",
  "no_index": {
    "directory": [
      "t",
      "inc"
    ]
  },
  "release_status": "stable",
  "resources": {
    "repository": {
      "type": "git",
      "url": "git://github.com/lskatz/endopep_peaks.git",
      "web": "https://github.com/lskatz/endopep_peaks"
    }
  },
  "version": "v3.2.1"
}
```

It works with ExtUtils::MakeMaker version 7.46.
https://github.com/shogo82148/endopep_peaks/runs/1172090538

```json
{
  "abstract": "unknown",
  "author": [
    "Lee S. Katz <gzu2@cdc.gov>"
  ],
  "dynamic_config": 0,
  "generated_by": "ExtUtils::MakeMaker version 7.46, CPAN::Meta::Converter version 2.143240",
  "license": [
    "mit"
  ],
  "meta-spec": {
    "url": "http://search.cpan.org/perldoc?CPAN::Meta::Spec",
    "version": "2"
  },
  "name": "Endopep_peaks",
  "no_index": {
    "directory": [
      "t",
      "inc"
    ]
  },
  "prereqs": {
    "build": {
      "requires": {
        "Test::More": "0.47"
      }
    },
    "configure": {
      "requires": {
        "ExtUtils::MakeMaker": "0"
      }
    },
    "runtime": {
      "requires": {
        "Array::IntSpan": "2.004",
        "Data::Dumper": "0",
        "File::Basename": "0",
        "File::Which": "0",
        "FindBin": "0",
        "Getopt::Long": "0",
        "Spreadsheet::XLSX": "0",
        "perl": "5.016000"
      }
    }
  },
  "release_status": "stable",
  "resources": {
    "repository": {
      "type": "git",
      "url": "git://github.com/lskatz/endopep_peaks.git",
      "web": "https://github.com/lskatz/endopep_peaks"
    }
  },
  "version": "v3.2.1"
}
```

I recommend you to add [cpanfile](https://metacpan.org/pod/distribution/Module-CPANfile/lib/cpanfile.pod) into your repository.
`cpanm` can read `cpanfile` directly.

**Comment by lskatz** [comment]
Thank you for your help!  I don't know if I would have caught that!

**Comment by mohawk2** [comment]
I'm seeing something extremely similar, but only on 5.14: https://github.com/graphviz-perl/GraphViz2/commit/c289cd2f3e0f409bff18da356632e0825afcd674 gives similar results: https://github.com/graphviz-perl/GraphViz2/runs/1359196992. There are no shenanigans in the `Makefile.PL`. Can you help?
