### ISSUE TITLE
multithreading

### ISSUE THREAD

**Issue by lskatz** [shogo82148/actions-setup-perl#420]
Hi, how do I specify using a perl version with multithreading?

**Comment by shogo82148** [comment]
Currently, there is no way to specify using multithreading.
If I get a lot of requests, I might implement it.

**Comment by DrHyde** [comment]
I'd like to be able to use a perl with thread support too.

**Comment by shogo82148** [comment]
https://github.com/marketplace/actions/setup-perl-environment#action-inputs
the `multi-thread` option is now available 🎉

**Comment by DrHyde** [comment]
Thanks!

**Comment by lskatz** [comment]
Thank you!!
