### ISSUE TITLE
Support Perl 5.6.1, 5.6.2, and 5.8.x (where x < 5)

### ISSUE THREAD

**Issue by tobyink** [shogo82148/actions-setup-perl#450]
Would be really nice to have support for those.

Yes, I know `cpanm` doesn't work on Perl older than 5.8.1, so the classic CPAN client would need to be used there.

**Comment by tobyink** [comment]
Actually `cpanm` is really easy to get working on Perl 5.6.

Here's an example of a working cpanm for Perl 5.6. (Tested on 5.6.1 and 5.6.2.)

https://gist.github.com/tobyink/c7a1001f39d90c3ff76400b13183b268

A summary of changes:

* `print$fh JSON::PP::encode_json($local)` needs to be changed to `print {$fh} JSON::PP::encode_json($local)` — this is just one place in the fatpacked App::cpanminus::script.
* `use 5.008001` needs to be changed to `use 5.006` in fatpacked CPAN::Meta::YAML.
* In fatpacked App::cpanminus::script, where it calls GetOptions, the `q|quiet!` option should be changed to `q|quiet`, `n|notest!` changed to `n|notest` and `S|sudo!` changed to `S|sudo`. This means that `--no`-prefixed versions of those options stop working, but they're already false by default.

So if actions-setup-perl could install a patched version of `cpanm` with the above fixes, this would make testing on Perl 5.6 work beautifully.

**Comment by shogo82148** [comment]
fixed by https://github.com/shogo82148/actions-setup-perl/pull/481 and https://github.com/shogo82148/actions-setup-perl/pull/453
