### ISSUE TITLE
Cannot use IO::Socket::SSL on windows

### ISSUE THREAD

**Issue by skaji** [shogo82148/actions-setup-perl#462]
I assume shogo82148/actions-setup-perl now contains IO::Socket::SSL by default,
but it seems that we cannot require it on windows.

Minimal example:
```
name: test

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.14'
      - run: perl -MIO::Socket::SSL -e1
```

and its output:
https://github.com/skaji/github-actions-playground/runs/1430628950?check_suite_focus=true
```
2020-11-20T12:01:21.4440637Z ##[group]Run perl -MIO::Socket::SSL -e1
2020-11-20T12:01:21.4441480Z [36;1mperl -MIO::Socket::SSL -e1[0m
2020-11-20T12:01:21.4529565Z shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
2020-11-20T12:01:21.4530122Z env:
2020-11-20T12:01:21.4531711Z   PERL5LIB: D:\a\_actions\shogo82148\actions-setup-perl\v1\scripts\lib
2020-11-20T12:01:21.4532324Z ##[endgroup]
2020-11-20T12:01:26.6244178Z ##[error]Process completed with exit code 1.
```

**Comment by shogo82148** [comment]
fixed by https://github.com/shogo82148/actions-setup-perl/pull/474

**Comment by skaji** [comment]
@shogo82148 Thank you.

But it seems that now `Run shogo82148/actions-setup-perl@v1` itself fails.
workflow file: https://github.com/skaji/github-actions-playground/actions/runs/374301534/workflow
output: https://github.com/skaji/github-actions-playground/runs/1483606023

**Comment by shogo82148** [comment]
I just published v1.9.0, but it is currently unavailable.
Because of the problem of my releasing flow https://github.com/shogo82148/actions-setup-perl/issues/493

Please wait a little. I'll notify you when v1.9.0 is available.

**Comment by shogo82148** [comment]
Thank you for waiting.
Uploading binaries has finished, and v1.9.0 is now available.
Please try it!

**Comment by skaji** [comment]
@shogo82148  It works now. Thank you again.

**Comment by oalders** [comment]
Thanks @shogo82148 and @skaji!
