### ISSUE TITLE
MacOS has suddenly started failing

### ISSUE THREAD

**Issue by mohawk2** [shogo82148/actions-setup-perl#492]
https://github.com/graphviz-perl/Graph/runs/1483639131 shows

```
Run shogo82148/actions-setup-perl@v1
  with:
    distribution: strawberry
    perl-version: 5
Warning: The strawberry distribution is not available on this platform. fallback to the default distribution.
```

This is a breaking change, previously specifying "strawberry" was a no-op on non-Windows.

Edited to add: Also, your CI has been failing since 2 days ago?

**Comment by mohawk2** [comment]
And now it fails with no distro specified on both Windows AND MacOS: https://github.com/graphviz-perl/Graph/runs/1483701921

**Comment by shogo82148** [comment]
I just published v1.9.0, but it is currently unavailable.
Because of the problem of my releasing flow https://github.com/shogo82148/actions-setup-perl/issues/493

Please wait a little. I'll notify you when v1.9.0 is available.

**Comment by shogo82148** [comment]
Thank you for waiting.
Uploading binaries has finished, and v1.9.0 is now available.
Please try it!

**Comment by mohawk2** [comment]
Thank you, I can confirm it's working again! Are you aware of @perl-actions btw? We have in mind to expand it to have more than just module-installation actions.

**Comment by shogo82148** [comment]
Yes, I do
