### ISSUE TITLE
Action breaks SSL certificate verification

### ISSUE THREAD

**Issue by sidey79** [shogo82148/actions-setup-perl#562]
Since yesterday i get some errors using wget to download files.

This seems to bei a known problem after installing openssl 1.1.1.

I am getting error that certificate authority can't bei checked.
I checked for changes in the used actions and figured out that your action changes openssl in the Runner.

Here some usefull infos about that problem.

https://medium.com/@brunoosiek/updating-openssl-latest-and-greatest-version-in-ubuntu-18-04-8f10ba4e2377

Can you pleased revert your Changes in this?
May ist's also not a good idea to change the runners environment in such a way, that it affects all other actions.

**Comment by sidey79** [comment]
@shogo82148 

Just to inform you. The v1 tag still points to a commit that has the bug.
So i still have broken workflows.

**Comment by shogo82148** [comment]
I released it as [v.1.9.4](https://github.com/shogo82148/actions-setup-perl/releases/tag/v1.9.4).
Thanks.
