### ISSUE TITLE
Problem with Perl path on self-hosted runner

### ISSUE THREAD

**Issue by ekarlso** [shogo82148/actions-setup-perl#643]
It seems that the code for the PERLLIB logic is assuming that the path is going to be __dirname something which causes the path to be built up badly:

Can't locate strict.pm in @INC (you may need to install the strict module) (@INC contains: /home/runner/_work/_actions/shogo82148/actions-setup-perl/v1/scripts/lib /opt/hostedtoolcache/perl/5.32.1/x64/lib/site_perl/5.32.1/x86_64-linux /opt/hostedtoolcache/perl/5.32.1/x64/lib/site_perl/5.32.1 /opt/hostedtoolcache/perl/5.32.1/x64/lib/5.32.1/x86_64-linux /opt/hostedtoolcache/perl/5.32.1/x64/lib/5.32.1)

When on a self-hosted runner the hostedtool cache folder is going to be /home/runner/_work/_tool/perl/... instead of /opt...

**Comment by shogo82148** [comment]
Unfortunately, actions-setup-perl doesn't support self-hosted runner.
The action uses binaries built on GitHub hosted runner and the binaries are not portable.

Please consider using Docker images or building perl binary on your machine.

**Comment by ylavoie** [comment]
Same issue running on Github Actions with actions-setup-perl used as a container. Not supported either?
