### ISSUE TITLE
cpm destination directory

### ISSUE THREAD

**Issue by ylavoie** [shogo82148/actions-setup-perl#684]
Although $RUNNER_TOOL_CACHE is fixed per platform, it should be documented to allow end users to cache their installed modules by the provided cpanm or cpm.

**Comment by shogo82148** [comment]
Sounds good, but it is too difficult for many people to configure caching correctly.
So I'm working to implement caching function into actions-setup-perl. https://github.com/shogo82148/actions-setup-perl/pull/686

**Comment by shogo82148** [comment]
released as v1.11.0
https://github.com/shogo82148/actions-setup-perl/releases/tag/v1.11.0
