### ISSUE TITLE
Feature: Add Variable for Current Version

### ISSUE THREAD

**Issue by theory** [shogo82148/actions-setup-perl#885]
I've started using the cache action to cache CPAN downloads. It needs to be keyed on the processor architecture and the Perl version. I'm using `${{ runner.os }}-perl5lib-${{ matrix.perl }}`, but sometimes I'm just using "latest" ([example](/github.com/sqitchers/sqitch/blob/develop/.github/workflows/pg.yml)), and if there is a new release, the cache would not be compatible with the the perl version. Is there a way to identify the current version of Perl aside from the matrix? Would be nice if there were variables to indicate the major and minor versions of Perl after Perl is setup.

**Comment by shogo82148** [comment]
fixed by https://github.com/shogo82148/actions-setup-perl/pull/892
see the Action outputs section https://github.com/shogo82148/actions-setup-perl#action-outputs
